name: my_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  get: ^4.7.3
  fluttertoast: ^9.0.0
  google_sign_in: ^6.2.1
  flutter_dotenv: ^6.0.0
  cloud_firestore: ^6.1.1
  firebase_messaging: ^16.1.0
  image_picker: ^1.2.1
  flutter_local_notifications: ^19.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
